name: Pull request and build workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/npm-test.yaml
      - uses: ./.github/workflows/build-and-push-image.yaml
