name: Pull request and build workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request:
    steps:
      uses: ./.github/workflows/npm-test.yaml
      uses: ./.github/workflows/build-and-push-image.yaml
