name: Send custom JSON data to Slack workflow

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        description: 'A webhook URL for the specific Slack integration'
        required: true

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v2.0.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "repository": "${{ github.repository }}",
              "branch": "${{ github.ref_name }}",
              "status": "${{ job.status }}",
              "user": "${{ github.actor }}",
              "commit": "${{ github.sha }}",
              "action_name": "${{ github.workflow }}",
              "job_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "image_link": "https://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}