name: Generate SBOM using Syft

on:
  workflow_call:
    inputs:
      registry:
        required: true
        description: 'The registry where our image is located'
      image_name:
        required: true
        description: 'The image name we want to generate the SBOM for'

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0
        with:
          image: ${{ inputs.registry }}/${{ inputs.image_name }}:latest
          dependency-snapshot: true
    